vich_uploader:
    db_driver: orm

    mappings:
        modeles_image:
            uri_prefix: /images/modeles
            upload_destination: '%kernel.project_dir%/public/images/modeles'
            delete_on_remove: false